<%@ page language="java" contentType="text/html; charset=UTF-8"	pageEncoding="UTF-8"%>
<%@ include file="../base/path.jsp"%>
<script type="text/javascript" src='<%=path%>/resources/js/jquery/jquery-2.1.3.min.js'></script>
<script type="text/javascript" src='<%=path%>/resources/js/bootbox.min.js'></script>
<%--<script type="text/javascript" src="<%=path%>/resources/js/jquery/jquery.cookie.js"></script>--%>
<script type="text/javascript" src="<%=path%>/resources/js/jquery/jquery.i18n.properties-min-1.0.9.js"></script>
<script type="text/javascript" src="<%=path%>/resources/js/jquery/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<%=path%>/resources/js/bootstrap/bootstrap.js"></script>
<script type="text/javascript" src="<%=path%>/resources/js/bootstrap/bootstrap-colorpicker.min.js"></script>
<script type="text/javascript" src="<%=path%>/resources/js/bootstrap/bootstrap-tag.min.js"></script>
<script type="text/javascript" src="<%=path%>/resources/js/bootstrap/bootstrapValidator.min.js"></script>
<script type="text/javascript" src="<%=path%>/resources/js/select2.full.js"></script>
<script type="text/javascript" src="<%=path%>/resources/js/handlebars-v3.0.3.js"></script>
<script type="text/javascript" src="<%=path%>/resources/js/bootstrap/bootstrap-select.js"></script>
<script type="text/javascript" src='<%=path%>/resources/js/dataTables.bootstrap.js'></script>
<script type="text/javascript" src="<%=path%>/resources/js/typeahead-bs2.min.js"></script>
<script type="text/javascript" src="<%=path%>/resources/js/My97DatePicker/WdatePicker.js"></script>
<script type="text/javascript" src="<%=path%>/resources/js/ace/ace.all.js"></script>
<%--<script type="text/javascript" src="<%=path%>/resources/js/example.js"></script>--%>
<script type="text/javascript" src="<%=path%>/resources/js/interfaces/util.js"></script>
